version: '3.8'

services:
  spring:
    build: src/main
    container_name: SUN_back_app
    ports:
      - "8080:8080"
    networks:
      - app_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: sun
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data